param(
    [Parameter()]
    [string]$TaskName = 'Codex Usage Widget Watchdog'
)

$ErrorActionPreference = 'Stop'
$repoRoot = [IO.Path]::GetFullPath($PSScriptRoot)
$sourceWidget = Join-Path $repoRoot 'CodexTaskbarWidget.exe'
$sourceWatchdog = Join-Path $repoRoot 'scripts\watch-codex.ps1'

foreach ($requiredPath in @($sourceWidget, $sourceWatchdog)) {
    if (-not (Test-Path -LiteralPath $requiredPath -PathType Leaf)) {
        throw "Required file was not found: $requiredPath"
    }
}

$widgetVersion = [version](Get-Item -LiteralPath $sourceWidget).VersionInfo.FileVersion
if ($widgetVersion -lt [version]'2.1.3.0') {
    throw 'Use the package generated by scripts\Build-Release.ps1. The repository-root EXE is a previous release.'
}

$runtimeRoot = [IO.Path]::GetFullPath(
    (Join-Path $env:LOCALAPPDATA 'CodexUsageWidget\watchdog'))
$runtimeWidget = Join-Path $runtimeRoot 'CodexTaskbarWidget.exe'
$runtimeWatchdog = Join-Path $runtimeRoot 'watch-codex.ps1'
New-Item -ItemType Directory -Path $runtimeRoot -Force | Out-Null
Copy-Item -LiteralPath $sourceWidget -Destination $runtimeWidget -Force
Copy-Item -LiteralPath $sourceWatchdog -Destination $runtimeWatchdog -Force

$legacyTask = Get-ScheduledTask -TaskName 'ChatGPT Codex Usage Widget' -ErrorAction SilentlyContinue
if ($null -ne $legacyTask) {
    Disable-ScheduledTask -TaskName $legacyTask.TaskName -ErrorAction SilentlyContinue | Out-Null
    Unregister-ScheduledTask -TaskName $legacyTask.TaskName -Confirm:$false
}

$startupDirectory = [Environment]::GetFolderPath('Startup')
foreach ($shortcutName in @('ChatGPT Codex Usage Widget.lnk', 'Codex Taskbar Widget.lnk')) {
    $shortcutPath = Join-Path $startupDirectory $shortcutName
    if (Test-Path -LiteralPath $shortcutPath) {
        Remove-Item -LiteralPath $shortcutPath
    }
}

$runKey = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Run'
Remove-ItemProperty -Path $runKey -Name 'ChatGPTCodexUsageWidget' -ErrorAction SilentlyContinue
Remove-ItemProperty -Path $runKey -Name 'CodexTaskbarWidget' -ErrorAction SilentlyContinue

$userSid = [Security.Principal.WindowsIdentity]::GetCurrent().User.Value
$powershellPath = Join-Path $env:SystemRoot 'System32\WindowsPowerShell\v1.0\powershell.exe'
$actionArguments = "-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File `"$runtimeWatchdog`" -WidgetPath `"$runtimeWidget`""
$eventQuery = "<QueryList><Query Id='0' Path='Microsoft-Windows-AppModel-Runtime/Admin'><Select Path='Microsoft-Windows-AppModel-Runtime/Admin'>*[System[Provider[@Name='Microsoft-Windows-AppModel-Runtime'] and EventID=201]] and *[EventData[Data[@Name='ApplicationName']='OpenAI.Codex_2p2nqsd0c76g0!App']]</Select></Query></QueryList>"

$escapedTaskName = [Security.SecurityElement]::Escape($TaskName)
$escapedSid = [Security.SecurityElement]::Escape($userSid)
$escapedPowerShell = [Security.SecurityElement]::Escape($powershellPath)
$escapedArguments = [Security.SecurityElement]::Escape($actionArguments)
$escapedRuntimeRoot = [Security.SecurityElement]::Escape($runtimeRoot)
$escapedEventQuery = [Security.SecurityElement]::Escape($eventQuery)

$taskXml = @"
<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.4" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>Run the bundled Codex usage widget only while the Codex desktop app is open.</Description>
    <URI>\$escapedTaskName</URI>
  </RegistrationInfo>
  <Triggers>
    <EventTrigger>
      <Enabled>true</Enabled>
      <Subscription>$escapedEventQuery</Subscription>
    </EventTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <UserId>$escapedSid</UserId>
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>false</AllowHardTerminate>
    <StartWhenAvailable>false</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>true</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>$escapedPowerShell</Command>
      <Arguments>$escapedArguments</Arguments>
      <WorkingDirectory>$escapedRuntimeRoot</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
"@

Register-ScheduledTask -TaskName $TaskName -Xml $taskXml -Force | Out-Null

$codexIsRunning = Get-CimInstance Win32_Process -Filter "Name = 'ChatGPT.exe'" -ErrorAction SilentlyContinue |
    Where-Object {
        $_.ExecutablePath -match '(?i)\\WindowsApps\\OpenAI\.Codex_' -and
        ([string]::IsNullOrWhiteSpace($_.CommandLine) -or
         $_.CommandLine -notmatch '(?i)(^|\s)--type=')
    } |
    Select-Object -First 1
if ($null -ne $codexIsRunning) {
    Start-ScheduledTask -TaskName $TaskName
}

Write-Host "Installed scheduled watchdog: $TaskName"
Write-Host 'It is triggered by the Codex app event, not by Windows sign-in.'
Write-Host "Runtime files: $runtimeRoot"
